qwen:
  zipfile_path: 'path\\to\\zipfile'
  test_folder_name: 'test_im'
  test_extract_folder: 'folder_name'
  train_folder_name: 'train_im'
  train_extract_folder: 'folder_name'
  sampled: 'folder_name'
  sample_size: 200
  
pixtral:

minicpm: